### ISSUE TITLE
[Enhancement]: Create User 的参数解释详尽一些

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#100]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/31049447/203959818-27d542c1-a65c-4f00-bdf1-3213754026ce.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/184
