### ISSUE TITLE
[Enhancement]: 增加描述下 Drop Account/User/Role 后的产品行为

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#101]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

文档中没有介绍，行为应该是 立即终止正在连接的 用户session

**Comment by lacrimosaprinz** [comment]
@domingozhang   潇哥  这个该怎么终止正在连接的用户会话？sql语句是什么？

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/173
