### ISSUE TITLE
[Enhancement]: 更好的 set role 示例

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#102]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1、这个优先级低：文中是授权所有的表的增改权限，其实可以支持对某个表的增改权限修改
2、这个优先级稍微高点：解释一下示例做的事，权限这块用户理解起来有点困难。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/185
