### ISSUE TITLE
[Typo]: public role 不能 revoke

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#103]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/31049447/203962445-f30a5086-455f-4352-87d4-66e51e675499.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/173
