### ISSUE TITLE
[Enhancement]: 非 sysaccount 中的系统表没有必要强调 view

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#104]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/31049447/203962725-23e6a389-8e11-4f88-bc08-80050fae7270.png">

 本身系统表也不允许修改，而强调view 的话会让人觉得不能修改，那就会进一步让用户错误的推理成本应该可以修改，这个逻辑有些怪

**Comment by dengn** [comment]
已修订。
