### ISSUE TITLE
[Typo]: MO 系统库中大量描述不正确

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#105]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

1、标题叫 catalog，但里面介绍了所有的系统库
2、几乎所有的表的列类型跟现有 MO 类型对不上
3、很多列的描述太过于直白以至于跟没说一样，例如 主键、用户ID（至少写成创建这张表的用户 ID）
4、mo_global_variables 没有这张表
5、标题错了：xxxxxx user -> xxxxxxx table
6、system_metrics 中 少了 account 这列，多了 internal 这列
7、system_metrics.metrics -> system_metrics.metric

**Comment by dengn** [comment]
已修订
