### ISSUE TITLE
[Enhancement]: Slow query sql error

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixorigin.io.cn#113]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/cn/dev/MatrixOne/Troubleshooting/slow-queries/#_2
1.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/43231571/204204986-e5e39623-efa5-4f68-aa47-b8694fda78c1.png">
这一串sql报错如下：
> create view error_sql as select si.request_at time_stamp,si.statement as SQL,el.err_code from statement_info si,error_info el where si.statement_id=el.statement_id and user<>'internal';
ERROR 1064 (HY000): SQL parser error: table "statement_info" does not exist

2. 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/43231571/204205496-4d6493d7-9bf4-4618-955e-29608ffad25a.png">
查询SQL错误的命令也是报错，需要给出完整的建表语句
> select * from mo_ts.error_sql;
ERROR 1064 (HY000): SQL parser error: table "error_sql" does not exist

**Comment by domingozhang** [comment]
错误日志DDL改为：
create view error_sql as select si.request_at time_stamp,si.statement,si.error as SQL from system.statement_info si where si.user<>'internal' and si.status='Failed' ;

即可重新获取
