### ISSUE TITLE
[Typo]: 描述中的表名与sql中的不一致

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#116]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/31049447/204433560-0d5ac13d-6ad0-41e4-9576-d7ff7369a0b0.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/127
