### ISSUE TITLE
[Enhancement]: select ... into outfile 特性介绍不正确或不清晰

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#117]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

- select ... into 权限 -> select 权限
- 产品行为是不能覆盖已存在的文件，后半句的注意好像没有必要。
- 拥有可登录账户，不是很明确它的意思，是让 outifile 目录下具有什么权限吗？
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/31049447/204434034-4619b87d-6330-4356-bcd8-1bb20d7771c2.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/173
