### ISSUE TITLE
[Enhancement]: 没有说明怎么安装Operator的前置依赖

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#129]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/4965857/205543675-50fa20c7-56dc-4b42-bcb9-a90f74d4054c.png">

没有怎么安装的说明。
以及如何检查是不是安装了。

**Comment by lacrimosaprinz** [comment]
0.7安装过程颠覆0.6版本
