### ISSUE TITLE
[Typo]: Java CURD 文档中的描述错误

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#130]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/31049447/206099938-c46a93db-0630-4556-9e75-9b2fe302f829.png">
- github 建议改成 java_crud_example 之类的
- 0.5.1 -> 0.6.0
- 升级数据->更新数据

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/165
