### ISSUE TITLE
[Displaying]: 应用开发示例中的图挂了

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#132]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

Hibernate, MyBatis的图挂了
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/31049447/206102462-c18a4971-2167-465e-9288-d9c2d429f844.png">

**Comment by lacrimosaprinz** [comment]
Fixed: https://docs.matrixorigin.io/cn/0.6.0/MatrixOne/Tutorial/springboot-hibernate-crud-demo/#2-intellij-idea-spring-boot
