### ISSUE TITLE
[Displaying]: Hibernate 里的 application.properties 中单词拼写错误

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#134]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/31049447/206103431-8ff02019-4ef8-4839-b0a9-29a1ea376e2f.png">
- paratemers->parameters

**Comment by lacrimosaprinz** [comment]
https://docs.matrixorigin.io/cn/0.6.0/MatrixOne/Tutorial/springboot-hibernate-crud-demo/#2-intellij-idea-spring-boot   已修正
