### ISSUE TITLE
[Typo]: Hibernate 项目代码缺少 jar 包

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#135]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/31049447/206104057-cee27544-7f72-4e57-8a33-cfea0d36487c.png">

- 缺少 javax。可以引导用户下载 toplink-essentials.jar 和 toplink-essentials-agent.jar，或者让用户在 prom.xml 中加入相关 dependency

**Comment by lacrimosaprinz** [comment]
https://docs.matrixorigin.io/cn/0.6.0/MatrixOne/Tutorial/springboot-mybatis-crud-demo/#1-usercontrollerjava  @LiSong0214 @dengn  待确认内容是否正确
