### ISSUE TITLE
[Typo]: select 翻译中文错误

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#138]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/31049447/206128435-7305ab29-6c7e-4a61-ada2-f2f5675a4aea.png">
选择->查询/查找

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/164
