### ISSUE TITLE
[Enhancement]: ORM 介绍优化

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#139]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

内容与 MyBatis 和 Hibernate 重复，建议考虑删掉这一章

**Comment by lacrimosaprinz** [comment]
这个示例也更新了：https://docs.matrixorigin.io/0.6.0/MatrixOne/Tutorial/springboot-mybatis-crud-demo/
https://docs.matrixorigin.io/0.6.0/MatrixOne/Tutorial/springboot-hibernate-crud-demo/
