### ISSUE TITLE
[Enhancement]: Python 应用示例优化

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#140]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

- 股票分析的数据需要用户去 Tushare 下载，而注册用户的积分一般不够，用户体验无法简单完成，要么考虑下载好，存到git 上让用户使用？
- 安装 pymysql，建议引导用户使用命令行安装
> pip3 install pymysql
- create database stock. -> create database stock;
- 文档的介绍逻辑建议改一下：可以以项目示例中的代码来介绍，如何使用 python 连接和使用 mo。（现在的代码跟项目中的不完全一样），最后可以介绍一下整个项目的接口使用。

**Comment by lacrimosaprinz** [comment]
这个示例下线了，补充了新的示例
