### ISSUE TITLE
[Displaying]: SQL-DDL CREATE DATABASE Part, the picture cannot be displayed

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixorigin.io.cn#148]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

![image](https://user-images.githubusercontent.com/35757205/207538065-66bdeca3-2163-4159-9117-73cada25854d.png)

**Comment by lacrimosaprinz** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/43231571/208120230-13455100-f96a-4ae5-a7f5-7b6a3c536b60.png">
是不是网络没加载出来？
