### ISSUE TITLE
[Displaying]: 建议将换行逗号调整至该行末尾

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#201]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

![image](https://user-images.githubusercontent.com/31049447/216582331-a2ae7f0f-8571-4284-8acd-eb3e796cbbae.png)

**Comment by lacrimosaprinz** [comment]
![Uploading image.png…]()
fixed
