### ISSUE TITLE
[Typo]: 单条导入章节内有的叫 supplier  有的叫 suppliers，导致插入失败

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#202]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/31049447/216583893-40cf2857-31c5-4d35-bea4-5786bc6e8cdc.png">

**Comment by lacrimosaprinz** [comment]
已修改
<img width="793" alt="image" src="https://user-images.githubusercontent.com/43231571/216883376-2ea097af-5311-4d5d-9746-937925dd4bd7.png">
