### ISSUE TITLE
[Typo]: MO 仅支持服务器端导入，不支持客户端本地导入

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#203]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/31049447/216584966-6396a208-e895-447d-a9b4-5334b300b293.png">

**Comment by lacrimosaprinz** [comment]
已修改：
<img width="852" alt="image" src="https://user-images.githubusercontent.com/43231571/216883899-de714af9-f558-4e34-9243-d4f9ddde709d.png">
