### ISSUE TITLE
[Enhancement]: 建议给个小的csv样例数据导入

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#204]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/31049447/216585894-5dc7b3f2-e011-4cb7-ade5-1ed78eea08cb.png">

**Comment by lacrimosaprinz** [comment]
@lacrimosaprinz
