### ISSUE TITLE
[Enhancement]: 增加select验证导入效果

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#205]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/31049447/216586762-8e0d44e5-166e-471d-bd0d-783868ed1395.png">

**Comment by lacrimosaprinz** [comment]
@lacrimosaprinz

**Comment by lacrimosaprinz** [comment]
查询到的表结构也是 t1啊，这里不用补充了吧
