### ISSUE TITLE
[Displaying]: 把 > 去掉，更容易被用户复制使用

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#206]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/31049447/216587028-5d369caf-7acd-4b23-b241-3a0bb229df2a.png">

**Comment by lacrimosaprinz** [comment]
这里第一轮0.6theme讨论时候聊过，讨论结果是：准备数据sql语句不加 >，查询语句加 mysql >
由于sql语句量比较大，所有修改优先级不高，遇到文档即修改。
这里我会改成
mysql> SELECT id, token FROM token_count;
