### ISSUE TITLE
[Enhancement]: 执行 modump 描述不清晰

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#207]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

![image](https://user-images.githubusercontent.com/31049447/216587968-b98b49cf-9057-4178-9587-7131cd54fd63.png)
看这里的描述，好像是在 mysql 里执行 modump

**Comment by lacrimosaprinz** [comment]
已修改
<img width="732" alt="image" src="https://user-images.githubusercontent.com/43231571/216897895-9db6f9fc-951c-48d3-9137-188f24d3b1e5.png">

**Comment by lacrimosaprinz** [comment]
且modump

**Comment by lacrimosaprinz** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/43231571/218018048-3e31927f-4b8d-4b78-afe6-daa9caf63289.png">
