### ISSUE TITLE
[Enhancement]: 增加 autocommit=0 的操作描述

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#208]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/31049447/216588354-100cac94-9ef2-4ff4-baca-a43ce1902f21.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/227
