### ISSUE TITLE
[Enhancement]: 增加一个复杂一点的隐式事务的例子

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#209]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

一些比较复杂的规则可以适当的举个例子
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/31049447/216588693-52e128fd-f7c1-432b-977f-952735de0833.png">

**Comment by lacrimosaprinz** [comment]
@domingozhang  潇哥，这里我细化了一下你看看对不对；   @LiSong0214 松哥，你看看这里简单介绍一下可以么
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/43231571/218379189-71edac46-3de1-4833-9dad-c34050f89009.png">
