### ISSUE TITLE
[Displaying]: 修改某行的值描述的很奇怪

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#210]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/31049447/216588886-d1c6875e-b40d-4acb-9f31-b84b6b19aeef.png">
描述很怪，要么叫做 FirstName 列的 Bob 值改为 Robert

**Comment by lacrimosaprinz** [comment]
已修改：
<img width="748" alt="image" src="https://user-images.githubusercontent.com/43231571/216880769-bc449f39-59f1-43a1-9e9d-6702d21e7f68.png">
