### ISSUE TITLE
[Displaying]: 命令写错了

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#212]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

![image](https://user-images.githubusercontent.com/31049447/216589559-536b4770-2371-443c-8246-b11a164a0a1c.png)

**Comment by lacrimosaprinz** [comment]
update.py

**Comment by lacrimosaprinz** [comment]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/43231571/218016887-c9db820b-d8da-468d-ab10-9b6ccd71184c.png">
已更新
