### ISSUE TITLE
[Enhancement]: 介绍一下 create account 命令中 status_option 的用法

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#213]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/31049447/216589901-66922f0b-7d9a-468d-9ea3-f625887e97ff.png">

**Comment by lacrimosaprinz** [comment]
这里木有  已删除
