### ISSUE TITLE
[Typo]:  grant 命令描述中关于用户和角色的描述不正确

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#214]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

![image](https://user-images.githubusercontent.com/31049447/216590112-7489a60e-ab3b-4658-abe7-711cb95de253.png)
root 是用户，权限归属于角色

**Comment by lacrimosaprinz** [comment]
修改：
<img width="782" alt="image" src="https://user-images.githubusercontent.com/43231571/216881928-afcc74bc-c30c-4550-a30a-24f525eeeb52.png">
