### ISSUE TITLE
[Displaying]: Error in blob query sample result

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixorigin.io.cn#260]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

mysql> create table blobtest (a blob);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into blobtest values('abcdef');
Query OK, 1 row affected (0.01 sec)

mysql> insert into blobtest values('_bcdef');
Query OK, 1 row affected (0.01 sec)

mysql> insert into blobtest values('a_cdef');
Query OK, 1 row affected (0.01 sec)

mysql> insert into blobtest values('ab_def');
Query OK, 1 row affected (0.00 sec)

mysql> insert into blobtest values('abc_ef');
Query OK, 1 row affected (0.01 sec)

mysql> insert into blobtest values('abcd_f');
Query OK, 1 row affected (0.00 sec)

mysql> insert into blobtest values('abcde_');
Query OK, 1 row affected (0.01 sec)

mysql> select * from blobtest where a like 'ab\_def' order by 1 asc;
+--------+
| a      |
+--------+
| ab_def |
+--------+
1 row in set (0.01 sec)

**Comment by lacrimosaprinz** [comment]
确认一下你使用的是mo的哪个版本，0.7.0版本执行结果是十六进制的结果，与mysql保持一致

**Comment by xuanyiLee** [comment]
是0.7.0版本







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "matrixorigin/matrixorigin.io.cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matrixorigin/matrixorigin.io.cn] [Displaying]: Error in blob query sample result (Issue #260)





 
确认一下你使用的是mo的哪个版本，0.7.0版本执行结果是十六进制的结果，与mysql保持一致

**Comment by lacrimosaprinz** [comment]
0.7.0 版本执行结果是16进制的结果，已经与 @heni02 确认
