### ISSUE TITLE
[Displaying]: timediff() 最后一个demo例子不完整，不知道要表达什么

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixorigin.io.cn#262]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

create table time_04 (t1 int,t2 time,t3 datetime,t4 timestamp); 
insert into time_04 values (1,"344:59:09","2020-09-12","2021-09-22 10:01:23.903"); 
mysql> select * from time_04; 
+------+-----------+---------------------+---------------------+ 
| t1 | t2 | t3 | t4 |
 +------+-----------+---------------------+---------------------+ 
| 1 | 344:59:09 | 2020-09-12 00:00:00 | 2021-09-22 10:01:24 | 
+------+-----------+---------------------+---------------------+

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/270
