### ISSUE TITLE
[Displaying]: 测试-》性能测试-》TPCC测试 标题错误

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixorigin.io.cn#277]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

![image](https://user-images.githubusercontent.com/35757205/224925312-331e3cbf-134c-4101-a49f-a035e82575da.png)
应为TPCC而不是TPCH

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/280
