### ISSUE TITLE
[Displaying]: 部署指南-》MatrixOne 分布式集群部署

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixorigin.io.cn#278]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

5. MatrixOne 集群部署
安装 matrixone-operator
使用如下命令行安装 matrixone-operator：
wget https://github.com/matrixorigin/matrixone-operator/archive/refs/tags/0.7.0.zip
unzip 0.7.0.zip
cd matrixone-operator-0.7.0/charts/matrixone-operator

以上地址不存在。
经检验上述命令应改为
wget https://github.com/matrixorigin/matrixone-operator/releases/download/0.7.0-alpha.1/matrixone-operator-0.7.0-alpha.1.tgz
tar -xvf matrixone-operator-0.7.0-alpha.1.tgz
cd /root/matrixone-operator/

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/282
