### ISSUE TITLE
[Displaying]: 部署指南-》MatrixOne 分布式集群部署-》

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixorigin.io.cn#279]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

4. MinIO 部署
启动成功后需要将9000端口暴露出去，文档中没有体现，否则后续mo-log模块无法连接9000端口
经测试执行下面命令：

nohup  kubectl port-forward --address 0.0.0.0  pod-name -n mostorage 9000:9000 &

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/282
