### ISSUE TITLE
[Doc Request]:"kill query/connection  documents"  need to be added

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixorigin.io.cn#298]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

Content is probably:

select connection_id();
kill query connection_id; 
kill connection connection_id;

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixone/issues/7349   待莫尘去修

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/299
