### ISSUE TITLE
[Enhancement]: 更新系统配置表

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#352]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Reference/System-Parameters/configuration-settings

0.8里面又增加了不少参数，需要做下更新。
目前已知的fileservice.cache的memory-capacity会影响性能，调大的话会变成类似分布式环境中，第一次查慢，后面多次查询就会变快。

以下是一个例子：
[metacache]
memory-capacity = "512MB"

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/354
