### ISSUE TITLE
[Enhancement]: 外键最关键的特性没讲出来

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#353]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/schema-design/data-integrity/foreign-key-constraints/

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/c04fa70f-1b32-46a8-8c20-5e900d8c78f8)

外键的值必须跟主表主键的值保持一致，不然就会报错，这是外键最核心的特性。但是文档里没有说到。

这篇文档写的不错，可以借鉴 http://c.biancheng.net/view/2441.html

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/360
