### ISSUE TITLE
[Enhancement]: field函数优化说明

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#362]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Reference/Functions-and-Operators/String/field/

这个函数有两点说明要补充一下：
1. 搜索字符串不区分大小写。
2. 如果有多个命中，只返回第一个的索引值。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/403
https://github.com/matrixorigin/matrixorigin.io.cn/pull/377
