### ISSUE TITLE
[Enhancement]: format函数的local语言指定表

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#363]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Reference/Functions-and-Operators/String/format/#_2

这个函数的[local]里面值的取值范围要明确下跟这个里面的local表取值保持一致。
https://dev.mysql.com/doc/refman/8.0/en/locale-support.html

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/378
https://github.com/matrixorigin/matrixorigin.io/pull/404
