### ISSUE TITLE
[Doc Request]: INSTR函数没有文档

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#365]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

https://github.com/matrixorigin/matrixone/issues/6652

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/379
https://github.com/matrixorigin/matrixorigin.io/pull/405
