### ISSUE TITLE
[Enhancement]: substring函数优化

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#367]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1. 例子错了，这是t1，不是t3。

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/20184fff-70b2-49b2-a3b1-dd75a7d7c6a2)

2. 现在支持from和for了

```
MySQL [test]> SELECT pub_name, SUBSTR(pub_name from 4 for 5) FROM t1 WHERE country='USA';
+--------------------------+------------------------+
| pub_name                 | substr(pub_name, 4, 5) |
+--------------------------+------------------------+
| Jex Max Publication      |  Max                   |
| Mountain Publication     | ntain                  |
| Summer Night Publication | mer N                  |
+--------------------------+------------------------+
3 rows in set (0.094 sec)
```

3. MID是substring的别名，现在也支持了。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/402
https://github.com/matrixorigin/matrixorigin.io.cn/pull/375
