### ISSUE TITLE
[Doc Request]: 正则表达式没有文档

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#368]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

https://github.com/matrixorigin/matrixone/issues/6655

MO的正则表达式已经实现的比较完善，与MySQL的功能范围基本保持一致。

https://dev.mysql.com/doc/refman/8.0/en/regexp.htm

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/409
https://github.com/matrixorigin/matrixorigin.io.cn/pull/387
