### ISSUE TITLE
[Enhancement]: enum没有生效

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#369]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Reference/Data-Types/enum-type

```
MySQL [test]> CREATE TABLE enumtable (
    ->     id INT NOT NULL AUTO_INCREMENT,
    ->     color ENUM('red', 'green', 'blue'),
    ->     PRIMARY KEY (id)
    -> );
ERROR 20102 (HY000): data type: 'enum' is not yet implemented

```
enum没有生效，可能要下线这篇文档。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/401
https://github.com/matrixorigin/matrixorigin.io.cn/pull/374
