### ISSUE TITLE
[Enhancement]: MO架构中的DN都改名叫Transaction Node简称TN

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#372]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

MO架构中的DN都改名叫Transaction Node简称TN

**Comment by lacrimosaprinz** [comment]
待确认，是否确认更名？ @domingozhang

**Comment by lacrimosaprinz** [comment]
docs edited:
https://github.com/matrixorigin/matrixorigin.io.cn/pull/669
https://github.com/matrixorigin/matrixorigin.io/pull/509
