### ISSUE TITLE
[Doc Request]: view概览

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#384]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

视图view是一个比较重要的feature，需要有一篇完整的说明，阐述MO目前的view支持情况，基本用法，以及使用场景。

类似这种https://www.yiibai.com/mysql/introduction-sql-views.html

可以放在这部分里。

<img width="352" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/45d93121-3b31-4b28-b9f3-8586e67e45cc">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/415
https://github.com/matrixorigin/matrixorigin.io.cn/pull/395
