### ISSUE TITLE
[Doc Request]:  临时表

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#385]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

MO支持临时表，但是没用信息完整的讲清楚支持哪些东西，以及怎么用这个东西。
现在只在create table的地方有一个字段说明，但是这个不太够。类似#384 ，都需要一个完整的概览及使用说明。

<img width="711" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/41610654-be28-4077-9093-49b590ea2b83">

可以参考https://www.yiibai.com/mysql/temporary-table.html

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/394
https://github.com/matrixorigin/matrixorigin.io/pull/414
