### ISSUE TITLE
[Doc Request]: 聚合函数

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#390]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

1. 聚合函数里面有个variance是支持的，貌似又这个文档，但是整体里没有体现。

<img width="1121" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/a3deb0eb-82d5-4561-a24e-731fb6ce84fb">

mysql> select variance(duration) from statement_info limit 10;
+--------------------+
| variance(duration) |
+--------------------+
|  2305314025734.005 |
+--------------------+
1 row in set (0.04 sec)

在MySQL里等同于var_pop函数。

2. sleep不是个聚合函数。可以创建个分类叫其他函数。类似mysql里的Miscellaneous Functions

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/412
https://github.com/matrixorigin/matrixorigin.io.cn/pull/392
