### ISSUE TITLE
[Doc Request]: mo_purge_log删除日志函数

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#401]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

函数章节增加一章，专门针对系统运维相关的。
mo_purge_log放在里面。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/458
https://github.com/matrixorigin/matrixorigin.io/pull/436
