### ISSUE TITLE
[Enhancement]: 外键约束章节更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#408]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/schema-design/data-integrity/foreign-key-constraints/

外键现在新增能力：
1. 多列外键支持，要体现一下，弄个例子。
2. 级联更新支持，on update cascade
3. 多层外键支持，父子孙的多级关系要体现一下。
4. alter table现在可以删除foreign key。
5. 现在的语法跟没写一样，外键的定义创建比这个复杂的多。
![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/db0ed395-cb33-4f2e-9183-7785b021db0e)

**Comment by lacrimosaprinz** [comment]
级联更新支持，on update cascade
