### ISSUE TITLE
[Doc Request]: UUID类型

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#422]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

https://github.com/matrixorigin/matrixone/issues/4019

mysql> create table t20(a uuid);
Query OK, 0 rows affected (0.02 sec)

mysql> show create table t20;
+-------+----------------------------------------------+
| Table | Create Table                                 |
+-------+----------------------------------------------+
| t20   | CREATE TABLE `t20` (
`a` UUID DEFAULT NULL
) |
+-------+----------------------------------------------+
1 row in set (0.01 sec)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/434
https://github.com/matrixorigin/matrixorigin.io.cn/pull/455
