### ISSUE TITLE
[Enhancement]: LOAD data描述重复

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#423]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/import-data/bulk-load/load-csv/#matrixone

<img width="806" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/37d97424-2786-41f5-ad81-4dec9db53d2d">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/436
