### ISSUE TITLE
[Enhancement]: unique key的限制去掉

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#424]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="724" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/00e0b73d-1d54-4086-9ccd-e35d1446d896">

```
CREATE TABLE `a1` (
`a` INT DEFAULT NULL
)
mysql> alter table a1 add unique( a);
Query OK, 0 rows affected (0.01 sec)
mysql> alter table a1 drop index a;
Query OK, 0 rows affected (0.00 sec)
```

**Comment by lacrimosaprinz** [comment]
已经去除了
