### ISSUE TITLE
[Typo]: json函数名字拼错了

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#425]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="820" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/fc73cfd9-4593-4bde-8902-6d65e268ba96">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/426
https://github.com/matrixorigin/matrixorigin.io.cn/pull/432
