### ISSUE TITLE
[Enhancement]: partition的描述不太正确

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#426]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Reference/Limitations/mo-partition-support/

https://github.com/matrixorigin/matrixorigin.io/pull/388

**Comment by lacrimosaprinz** [comment]
partition 删除rang 和 list 分区：https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUQvT2wHKeQzOd8YjuNo?scode=AJsA6gc3AA81XcCSdOAVcAqAZJACc

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/443
https://github.com/matrixorigin/matrixorigin.io/pull/431
