### ISSUE TITLE
[Enhancement]: Optimizer Hints章节下线

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#429]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Performance-Tuning/control-execution-plan/optimizer-hints/

几个问题：
1. 这个东西现在啥都不输出，相当于没有做。
2. 例子里面大量错误：表名对不上，order表名是关键字，无法建表成功。

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/b68658f6-a070-48b4-acc3-0d4a72e9dd04)

总的来说，目前这篇文档没有起到作用还增加了混淆，现在还是下掉。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/433
https://github.com/matrixorigin/matrixorigin.io/pull/427
