### ISSUE TITLE
[Enhancement]: 使用分区表调优 下线

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#430]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Performance-Tuning/optimization-concepts/through-partition-by/

这个现在也没有实际能力的时候连放在这个篇章的前提都没有，先下线吧。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/433
https://github.com/matrixorigin/matrixorigin.io/pull/427
