### ISSUE TITLE
[Enhancement]: 启动章节 配置文件路径不对

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#435]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="683" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/ff987318-8161-4618-9e9f-dbc8a48ce66b">

1. 二进制方式里现在的启动文件里面都只含了launch-tae-CN-tae-DN，quickstart文件夹没有包含。所以按照以前的启动路径是启动不了的。要把自己路径改成launch-tae-CN-tae-DN。
2. 要提醒一下用户MO的首次启动时间大概需要20-30秒，需要稍等一下才能拿MySQL客户端连接上。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/428
https://github.com/matrixorigin/matrixorigin.io.cn/pull/438
