### ISSUE TITLE
[Enhancement]: MatrixOne 功能特性 下线

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#439]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Overview/feature/feature-overview/

这篇在MatrixOne简介的时候基本覆盖了，现在比较重复，下线吧。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/441
https://github.com/matrixorigin/matrixorigin.io/pull/429
