### ISSUE TITLE
[Enhancement]: 发布订阅优化

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#440]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Develop/Publish-Subscribe/pub-sub-overview/

这章只解释了非常general的概念，然后一下子就到使用案例了。
中间没有文档解释这个在MO中的使用的说明是什么。

1. 最起码的信息，是谁跟谁之间的发布订阅？租户？表？数据库？
2. 订阅了之后会发生什么？上游更新下游也接着更新？上游删了下游也删？
3. 什么时候能订阅，什么时候不能订阅？

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/432
https://github.com/matrixorigin/matrixorigin.io.cn/pull/446
