### ISSUE TITLE
[Doc Request]: AUTO_INCREMENT自增约束

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#448]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

接#410，增加AUTO_INCREMENT自增约束的详细描述

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/456
https://github.com/matrixorigin/matrixorigin.io.cn/pull/559
