### ISSUE TITLE
[Doc Request]: 预处理

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#451]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

接#410，新增预处理章节， 完整描述MO的prepare相关用法

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/549
https://github.com/matrixorigin/matrixorigin.io/pull/453
