### ISSUE TITLE
[Doc Request]: 窗口函数

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#452]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

接#410， 新增窗口函数 章节

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/549
https://github.com/matrixorigin/matrixorigin.io/pull/453
