### ISSUE TITLE
[Doc Request]: 多租户概述

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#453]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

接#410，新增 多租户的整体概述

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/454
https://github.com/matrixorigin/matrixorigin.io.cn/pull/550
