### ISSUE TITLE
[Enhancement]: Medium int不支持

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#456]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

MO不支持MEDIUMINT，

在MySQL兼容性中要更新下。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/437
https://github.com/matrixorigin/matrixorigin.io.cn/pull/459
