### ISSUE TITLE
[Enhancement]: 下载安装包错误

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#460]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/defa5eda-b827-4d48-9e9a-3136822155f4)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/461
https://github.com/matrixorigin/matrixorigin.io/pull/438
