### ISSUE TITLE
[Enhancement]: 0.8的release note没有放在目录下

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#464]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/fc8fedb8-0478-40eb-b06b-ee4f31f4428b)

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Release-Notes/v0.8.0/

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/f674d3cc-5ef7-4c9b-868f-4d7ae999a15d)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/434
https://github.com/matrixorigin/matrixorigin.io.cn/pull/455
