### ISSUE TITLE
[Typo]: 关于默认值的部分描述无法理解

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixorigin.io.cn#479]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

文档地址：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Develop/schema-design/create-table/#_7
涉及内容：常见的，希望实现数据插入时，"可默认默认填充某个值的时间"。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/448
https://github.com/matrixorigin/matrixorigin.io.cn/pull/505
