### ISSUE TITLE
[Displaying]: linux使用源代码安装 4安装 MySQL Client出现homebrew

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixorigin.io.cn#487]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

linux使用源代码安装 4安装 MySQL Client出现homebrew

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/493
