### ISSUE TITLE
[Displaying]: Linux二进制安装  步骤 1：安装依赖出现homebrew

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixorigin.io.cn#488]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

Linux二进制安装  步骤 1：安装依赖出现homebrew

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/493
