### ISSUE TITLE
[Displaying]: 开发指南->数据库模式设计->创建表

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixorigin.io.cn#490]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

CREATE TABLE NATION(
N_NATIONKEY  INTEGER NOT NULL,
N_NAME       CHAR(25) NOT NULL,
N_REGIONKEY  INTEGER NOT NULL,
N_COMMENT    VARCHAR(152),
);
示例错误，N_COMMENT    VARCHAR(152)多了标点“，”

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/492
