### ISSUE TITLE
[Enhancement]: INSERT ON DUPLICATE KEY限制 错误

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#498]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/insert-on-duplicate/#_4

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/7c4b2d8d-451a-43c5-9c22-0a6235e2b110)

这两个限制条件是相互冲突的，究竟是支不支持唯一键？

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/447
https://github.com/matrixorigin/matrixorigin.io.cn/pull/501
