### ISSUE TITLE
[Enhancement]: linux安装里不涉及clang

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#499]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1/#_1

clang是mac里的东西，linux里面不需要体现。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/500
