### ISSUE TITLE
[Displaying]:步骤 5：连接 MatrixOne 服务里面的Note，点击"密码管理" ， 跳转后的新页面报404

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#503]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

文档链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2/#5-matrixone
路径 ：使用二进制包部署 
步骤 5：连接 MatrixOne 服务，的最下面Note描述里，参见[密码管理],  点击"密码管理"  跳转后的新页面报404
![1689064690379](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/8e31a124-11ad-42bb-a6b4-a608746e88dc)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/506

**Comment by yanghaitao5000** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
