### ISSUE TITLE
[Enhancement]: 根据matrixone文档操作，通过mo_ctl 工具启动 MatrixOne 服务时报错：提示日志目录未找到

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#504]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

文档链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2/#2
问题描述：
通过 “步骤 3：安装 mo_ctl 工具” 安装mo_ctl 工具，并配置MO_PATH=“/root/”后，
在“步骤 4：启动 MatrixOne 服务”中，执行 mo_ctl start 命令后，报错：提示找到日志文件=>"/data/mo_ctl/bin/start.sh: line 15: /root//matrixone/logs/stdout-20230711_161814.log: No such file or directory"，
而实际logs目录自动创建在了/root/目录下，并没有创建在文档描述的“/data/mo/logs/” 处，
除非手动创建：mkdir /root/matrixone/logs ，才能正常启动matrixone服务，
![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/f6b52587-f4f2-46da-ad2e-b0b307613beb)

**Comment by dengn** [comment]
是mo_ctl的bug，没有经过deploy的话这个matrixone/logs文件夹不会被创建。等mo_ctl修复
