### ISSUE TITLE
[Displaying]: 开发指南->应用开发示例->Golang 基础示例

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixorigin.io.cn#507]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

使用的docker环境，0.8.0的镜像
Successfully Created
panic: Error 20101 (HY000): internal error: panic unsupported type DATE:
github.com/matrixorigin/matrixone/pkg/sql/util.SetBytesToAnyVector
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/util/eval_expr_util.go:189
github.com/matrixorigin/matrixone/pkg/sql/compile.constructValueScanBatch
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:678
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:698
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:727
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:727
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:912
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1031
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1095
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:606
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:388
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:194
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/computation_wrapper.go:341
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2951
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3389
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3614
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:207
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:427
github.com/fagongzi/goetty/v2.(*server).doConnection
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:344
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

goroutine 1 [running]:
main.checkErr(...)
        /root/go_curd_demo/golang_crud_matrixone.go:80
main.main()
        /root/go_curd_demo/golang_crud_matrixone.go:27 +0x7d4
exit status 2

**Comment by dengn** [comment]
thanks @xuanyiLee , 确实是个bug
