### ISSUE TITLE
[Enhancement]: 按照docker方式部署，容器启动失败

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#508]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

文档目录：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method3/
部署服务器为8核16g，资源充足；
docker 服务服务active正常，版本为24.0.4
按照docker部署文档操作，拉取matrixorigin/matrixone:0.8.0 docker镜像后，容器启动失败，docker logs 发现如下报错：
![1689072970886](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/44f17c95-e4a1-460d-88f7-05f468a640fb)
![1689073028980](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/e64b8161-dfa3-4f37-b7c3-28eb69e195a1)
![1689073297495](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/0c17b0bc-0940-46b2-b305-52c843b4bb81)

**Comment by dengn** [comment]
@yanghaitao5000 可以明确一下你的操作系统版本么？

**Comment by yanghaitao5000** [comment]
@dengn CentOS Linux release 7.9.2009 (Core)

**Comment by dengn** [comment]
> @dengn CentOS Linux release 7.9.2009 (Core)

谢谢。已验证确实是个问题，目前可以先通过增加--privileged=true解决。
docker run -d -p 6001:6001 --name matrixone --privileged=true matrixorigin/matrixone:0.8.0

**Comment by loveRhythm1990** [comment]
maybe the same issue with: https://github.com/docker-library/golang/issues/467
