### ISSUE TITLE
[Enhancement]: docker启动都加上--privileged=true

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#518]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

根据#508 反馈的问题，在部分操作系统中可能碰到由于cgo引起的权限问题。
为屏蔽这个问题，文档中所有的docker启动命令都改成，

```
docker run -d -p 6001:6001 --name matrixone --privileged=true matrixorigin/matrixone:0.8.0
```

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/519
https://github.com/matrixorigin/matrixorigin.io/pull/449
