### ISSUE TITLE
[Enhancement]: mkdir加一个-p

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#546]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-macos/install-on-macos-method2/#1_1

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/acdd34a5-bd62-4c01-82ef-26b98b34145d)

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2/#2

![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/683bfa1e-c806-44a5-9e8b-29c492c08575)

![企业微信截图_16891299179820](https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/cb844bf7-4dcf-4ace-b687-4eb8dad6943a)

mkdir加一个-p，这样如果路径已经存在的话就不会报错

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/452
https://github.com/matrixorigin/matrixorigin.io.cn/pull/548
