### ISSUE TITLE
[Enhancement]: mo_ctl工具更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#551]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

mo_ctl 加了
1、uninstall.sh 卸载mo_ctl
2、mo_ctl uninstall 卸载mo
3、mo_ctl watchdog [status|disable|enable] 开启或关闭或查看mo保活状态
4、mo_ctl upgrade [cid] 升级或降级到指定commit id或者稳定的版本号

**Comment by lacrimosaprinz** [comment]
mo_ctl这个工具本身如何更新
