### ISSUE TITLE
[Displaying]: 中文文档里 存在 英文说明

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#552]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

链接地址：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/Operators/operators/comparison-functions-and-operators/not-equal/
问题：中文文档里 存在 英文说明
![1689251026093](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/533fbf05-74bc-47c0-84c3-b18c3d90fe0e)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/557
