### ISSUE TITLE
[Typo]: 文档中MatrixOne的默认用户有多处仍为dump，需修改为root

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixorigin.io.cn#577]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

在0.8版本，matrixone的默认用户应是从dump调整为了root，在"客户端工具连接"章节，有一些图片的截图中用户使用仍为dump，需要修改：
https://docs.matrixorigin.cn/0.8.0/MatrixOne/Develop/connect-mo/database-client-tools/#navicat-matrixone

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/460
