### ISSUE TITLE
[Displaying]: 链接跳转的页面不正确

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#592]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

文档链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/load-data/#_6

在CSV 格式标准说明 =》增加条件导入示例：
点击“导入. csv 格式数据” 跳转的地址不对，跳转到了“插入 jsonlines 文件” 页面了
如下图：
![1689583364832](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/bcaf9732-ac7c-407b-a585-635c39f4298f)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/461
https://github.com/matrixorigin/matrixorigin.io.cn/pull/593
