### ISSUE TITLE
[Displaying]: 中文页面显示英文描述

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#598]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

文档链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-index/
SHOW INDEX 页面有英文说明
如下图：
![1689594480343](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/2e3bf654-eccf-4e9b-ab55-ae5e13b806a9)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/604
