### ISSUE TITLE
[Displaying]: 页面无法编辑，报404

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#599]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

文档链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/SQL-Reference/Other/Prepared-Statements/prepared-statements-overview/

Prepared 语句概述 页面无法编辑，报错404

![1689595368948](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/8a598ad0-2c4a-4169-ba9f-5616521aa570)

**Comment by lacrimosaprinz** [comment]
这篇文章移除了，没有相关链接了，新的文档网站已部署：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/SQL-Reference/Other/Prepared-Statements/prepare/
