### ISSUE TITLE
[Displaying]: 中文页面里，参数描述却为英文

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#600]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Reference/SQL-Reference/Other/Explain/explain-workflow/#_2

位置：explain-workflow.md 

![1689596462506](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/610637b9-a6e9-42af-9f15-28f734057f42)

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/604
