### ISSUE TITLE
[Enhancement]: 集群部署：安装k8s之后，调整 DNS 路由表这块描述不清楚

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#605]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

链接：https://docs.matrixorigin.cn/0.8.0/MatrixOne/Deploy/deploy-MatrixOne-cluster/#kubernetes_3

位置：部署指南=》集群部署指南 =》开始安装 Kubernetes 集群
开始安装 Kubernetes 集群后，第5步中，在 Kubernetes 的每个节点上调整 DNS 路由表，……
这块描述不清楚
![1689674296084](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/14024128-9794-4f36-ace9-5014c5397bbf)

**Comment by dengn** [comment]
更新为

<img width="443" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/5692dadb-946f-4774-a39d-180eea0f5d49">

@lacrimosaprinz please update the doc.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/475
https://github.com/matrixorigin/matrixorigin.io.cn/pull/626
