### ISSUE TITLE
[Enhancement]: 事务行为更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#611]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Develop/Transactions/matrixone-transaction-overview/implicit-transaction/

现在有部分行为在这个上面没有体现出来。https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUrUmyCsU9TeaESgs1cL?scode=AJsA6gc3AA8fHhkLSQALQAjwY-ACU

另外与MySQL的差异点也没有单独说明，尤其在隐式数据自动提交行为上。

https://blog.csdn.net/weixin_45919793/article/details/124195969

可以看看这个issue的comment。https://github.com/matrixorigin/MO-Cloud/issues/936#issuecomment-1644876760

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/614
