### ISSUE TITLE
[Doc Request]: 系统相关函数

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#613]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

MO里有不少系统管理类的函数，
比如select user(), current_user(), current_role()这些。要挖掘一下然后补充一个列表。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/628
