### ISSUE TITLE
[Typo]: set_conf对象写错了

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#616]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1/#2-mo_ctl_1

<img width="722" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/9fe6e643-2125-4782-bd86-52bb0ca284a6">

这里第二个应该是MO_PATH，其他类似的地方也检查下是否有写错。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/468
https://github.com/matrixorigin/matrixorigin.io.cn/pull/617
