### ISSUE TITLE
[Typo]: 集群版部署修正dn副本数和pvc周期策略说明

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixorigin.io.cn#631]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

官网文档有2处小问题
1、dn副本数需要说明一下当前版本只能设置为1
2、这个是logservice使用的pvc的周期策略，不是s3
https://docs.matrixorigin.cn/0.8.0/MatrixOne/Deploy/deploy-MatrixOne-cluster/#matrixone
<img width="1590" alt="企业微信截图_00c8777a-54b2-4265-a0f1-b2b6cc4dd01c" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/46433151/e36bfe66-1854-4525-9444-9d548f2877aa">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/482
https://github.com/matrixorigin/matrixorigin.io.cn/pull/633
