### ISSUE TITLE
[Enhancement]: mysql_ssl_rsa_setup 工具安装检查描述优化

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#66]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1、没有 alias 或 export 很容易走不通
2、mysql 的 bin 目录一般会自带工具

建议改一下叙述逻辑告诉用户哪里可以安装，如何确认是否安装

**Comment by dengn** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/4965857/205194977-aa581288-cf07-4071-8ceb-748b6220c6a6.png">

另外0.6版本的配置文件路径变了，应该是
etc/launch-tae-logservice/cn.toml

**Comment by dengn** [comment]
fix by https://github.com/matrixorigin/matrixorigin.io.cn/pull/145
https://github.com/matrixorigin/matrixorigin.io/pull/184
