### ISSUE TITLE
[Typo]: .pem文件个数错了

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#67]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="789" alt="image" src="https://user-images.githubusercontent.com/31049447/202094816-35e7c453-b0c9-4e79-b93a-8a182763bddb.png">
是8个

**Comment by dengn** [comment]
fixed by https://github.com/matrixorigin/matrixorigin.io.cn/pull/146
