### ISSUE TITLE
[Displaying]:  更新MO的产品定位图

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#670]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

新图增加了向量类型

https://docs.matrixorigin.cn/dev/MatrixOne/Overview/matrixone-introduction/

英文版目前用的还是中文的图，也需要更新一下。
https://docs.matrixorigin.cn/en/0.8.0/MatrixOne/Overview/matrixone-introduction/

**Comment by lacrimosaprinz** [comment]
rename and update :https://gitee.com/matrixorigin/artwork/pulls/2

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/artwork/pull/47/files
