### ISSUE TITLE
[Enhancement]: 整体架构里面的streaming模块更新描述

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#677]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Overview/architecture/matrixone-architecture-design/#computing-node

**Comment by lacrimosaprinz** [comment]
doc edited:https://github.com/matrixorigin/matrixorigin.io.cn/pull/701
https://github.com/matrixorigin/matrixorigin.io/pull/513
