### ISSUE TITLE
[Doc Request]: streaming架构详解

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#678]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

<img width="296" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/ecbbc9d3-1a7c-4c2a-bfe9-7461d4cced49">

增加一篇完整for streaming的架构详解文章，参考存储引擎详解。

**Comment by lacrimosaprinz** [comment]
doc edited:https://github.com/matrixorigin/matrixorigin.io.cn/pull/701
https://github.com/matrixorigin/matrixorigin.io/pull/513
