### ISSUE TITLE
[Enhancement]: 更新最新动态的release note及所有的版本号

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#679]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Overview/whats-new/

**Comment by lacrimosaprinz** [comment]
update the number of version:
https://github.com/matrixorigin/matrixorigin.io/pull/512
https://github.com/matrixorigin/matrixorigin.io.cn/pull/700

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/517
https://github.com/matrixorigin/matrixorigin.io.cn/pull/706
