### ISSUE TITLE
[Typo]: SSL配置文件路径错误

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#68]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

这个要与0.6我们推荐的启动MO的路径保持一致，另外，应该不是cn1.toml，是 cn.toml。
此外，如果MO提供多个启动方式，建议在这里提醒用户，修改配置的路径要与MO启动路径保持一致
<img width="792" alt="image" src="https://user-images.githubusercontent.com/31049447/202095894-31b26770-d69f-4371-a419-a9a3664e169e.png">

**Comment by dengn** [comment]
fixed by https://github.com/matrixorigin/matrixorigin.io.cn/pull/145
