### ISSUE TITLE
[Enhancement]: matrixone主库的readme，中英文更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#680]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

目前matrixone主库的readme仍然是0.6时期的说法，都需要更新，安装部署的步骤也可以简化很多。

**Comment by yangj1211** [comment]
已更新：[#14757](https://github.com/matrixorigin/matrixone/pull/14757)
