### ISSUE TITLE
[Enhancement]: SQL的基本操作

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#682]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Get-Started/basic-sql/#matrixone-sql_1

增加replace语句的情况

**Comment by lacrimosaprinz** [comment]
doc edited:
https://github.com/matrixorigin/matrixorigin.io.cn/pull/707
https://github.com/matrixorigin/matrixorigin.io/pull/518
