### ISSUE TITLE
[Enhancement]: 默认悲观的更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#683]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/develop-overview/#matrixone

1.0版本是默认悲观的，这里的描述需要修改。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/702
https://github.com/matrixorigin/matrixorigin.io/pull/514
