### ISSUE TITLE
[Doc Request]: 如何切换事务的指南

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#684]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

目前1.0默认是悲观，但是我们也提供了乐观事务的选项，需要一篇指南告诉用户如何切换。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/521
https://github.com/matrixorigin/matrixorigin.io.cn/pull/712
