### ISSUE TITLE
[Enhancement]: 更新下截图里面的一些版本信息之类的东西

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#685]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/connect-mo/database-client-tools/

**Comment by cyann7** [comment]
@dengn 楠哥，我看了一下这个截图现在是mac的，而我现在的系统是windows的。如果上传windows的截图，用户是否会觉得有些奇怪，因为我们首页并没有说支持windows。
但是话说回来，这个只是mysql的client，其实并不矛盾，我要继续上传windows系统的截图并进行说明吗？

**Comment by cyann7** [comment]
https://github.com/matrixorigin/artwork/pull/50
