### ISSUE TITLE
[Enhancement]: 增加次级索引限制说明

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#688]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/schema-design/create-secondary-index/

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/703
https://github.com/matrixorigin/matrixorigin.io/pull/515
