### ISSUE TITLE
[Enhancement]: 增加MySQL到MO的DDL转储的限制说明

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#689]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/import-data/bulk-load/using-source/#_4

这里仍然会有部分不支持直接导入的情况存在，需要让用户去查我们的完整的支持清单，会有些非常明显的case仍然需要提示用户手动更改：

-decimal的精度
-mysql的bit类型

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/716
https://github.com/matrixorigin/matrixorigin.io/pull/524
