### ISSUE TITLE
[Doc Request]: 增加MySQL到MO DDL语句兼容性的说明列表

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#690]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

说明
-哪些语句可以无缝兼容
-哪些语句需要用户手动更改，更改方式是什么
-哪些语句无法兼容

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/716
https://github.com/matrixorigin/matrixorigin.io/pull/524
