### ISSUE TITLE
[Displaying]: csv的例子写错了

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#692]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="728" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/756bd247-c5b9-4250-a3a8-91cb2a094ca3">

**Comment by lacrimosaprinz** [comment]
doc edited:
https://github.com/matrixorigin/matrixorigin.io/pull/511
https://github.com/matrixorigin/matrixorigin.io.cn/pull/699
