### ISSUE TITLE
[Displaying]: 渲染问题

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#693]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="738" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/9db51659-f85f-44e5-b5d9-e382174bec61">

**Comment by lacrimosaprinz** [comment]
docs edited:
https://github.com/matrixorigin/matrixorigin.io/pull/510
https://github.com/matrixorigin/matrixorigin.io.cn/pull/698
