### ISSUE TITLE
[Enhancement]: CTE优化

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#694]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/dev/MatrixOne/Develop/read-data/cte/

说明目前我们支持递归CTE，另外增加一下到reference的链接。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/704
https://github.com/matrixorigin/matrixorigin.io/pull/516
