### ISSUE TITLE
[Enhancement]: DBeaver 连接 MO 后缺少两个系统库

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#70]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/31049447/202099720-badd0902-53ad-493a-8639-a83ad58752b3.png">
连接后缺损了 information_schema 和 mysql 两个库，经询问，是因为 dbeaver 默认不显示mysql的系统库，若要显示需要在连接视图中勾选显示系统对象。这个信息可以在手册里提一下。

**Comment by dengn** [comment]
英文版已修复 https://github.com/matrixorigin/matrixorigin.io/pull/185

**Comment by lacrimosaprinz** [comment]
中文已修复：https://docs.matrixorigin.io/cn/0.6.0/MatrixOne/Develop/connect-mo/database-client-tools/#dbeaver-matrixone
