### ISSUE TITLE
[Enhancement]: 启动配置文件路径变更

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#705]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

目前启动配置文件位置已经变更。文档里需要全部更新。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/710
https://github.com/matrixorigin/matrixorigin.io/pull/520
