### ISSUE TITLE
[Enhancement]: 使用 JDBC 连接 MO时，修改 Java 代码的路径没写清楚

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#71]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/31049447/202103799-b1877c07-1f44-4ce9-8b5b-f71ab95f036a.png">
应该是 src/main/java/io.mo/APP，建议加上

**Comment by lacrimosaprinz** [comment]
已修正：https://docs.matrixorigin.io/cn/0.6.0/MatrixOne/Develop/connect-mo/java-connect-to-matrixone/connect-mo-with-jdbc/#_2
