### ISSUE TITLE
[Typo]: Invalid mo-operator release download url

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixorigin.io.cn#718]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

mo-operator does not yet release v1.0 version, and it seems the download url is incorrect.

https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Deploy/deploy-MatrixOne-cluster/#matrixone-operator
```bash
wget https://github.com/matrixorigin/matrixone-operator/releases/download/chart-1.0.0-rc1-alpha.2/matrixone-operator-1.0.0-rc1-alpha.2.tgz
```
<img width="1089" alt="企业微信截图_9ee91768-26c0-4e74-9485-15d626286a27" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/46433151/93fd6283-e397-4773-b28a-3cea4da3c1ab">
<img width="1437" alt="企业微信截图_194ba14e-2496-4037-a0e1-a68bc56ca5bc" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/46433151/123a0b26-73a3-47d4-8d0c-d3a52511cf59">
<img width="1681" alt="企业微信截图_5c022205-28dc-4264-b2ba-3aefaf9efcad" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/46433151/ebb3ebb8-27d5-419a-a4b3-939cd12416be">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/719
