### ISSUE TITLE
[Enhancement]: 部署分布式集群在安装k8s时建议使用docker作为容器引擎

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixorigin.io.cn#732]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

部署分布式集群在安装k8s时建议使用docker作为容器引擎，建议强调一下。原因是一般docker使用较多，containerd使用较少，我们应该推荐docker为建议的容器引擎
https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Deploy/deploy-MatrixOne-cluster/#kubernetes_1

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/733
https://github.com/matrixorigin/matrixorigin.io/pull/535
