### ISSUE TITLE
[Doc Request]: 跨库事务的说明如何使用

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#735]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

MO支持跨database的事务，现在文档里没有地方说明。需要把这个feature和使用明确说明一下，一个简单的例子。

```
Start transaction;
insert into db1.table1 (field1) values (100),(100);
insert into db2.table2 (field2) values (100),(100);
commit;
```

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/537
https://github.com/matrixorigin/matrixorigin.io.cn/pull/737
