### ISSUE TITLE
[Typo]: 使用 root 用户创建数据库描述的不够严谨

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#74]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

MO 支持新建 account，在非默认account 中，需要使用拥有 accountadmin 角色的用户创建数据库等
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/31049447/202106943-44e31285-e9f1-41c8-ac30-821a0db89777.png">

**Comment by lacrimosaprinz** [comment]
https://docs.matrixorigin.io/dev/MatrixOne/Develop/schema-design/create-database/#view-databases   @LiSong0214   已修复
