### ISSUE TITLE
[Enhancement]: operator版本和使用管理更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#747]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Deploy/MatrixOne-Operator-mgmt/

operator已更新到1.0版本，需要把文档里的operator版本和使用更新

**Comment by yanghaitao5000** [comment]
ok， I'll handle it.
