### ISSUE TITLE
[Displaying]: 图要更新一下，dump改成root

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#751]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/artwork/docs/develop/navicat-config.png

**Comment by lacrimosaprinz** [comment]
腾讯云已更新：
<img width="1690" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/43231571/c9fc9116-1518-435d-83fa-e7ce81c977c5">
