### ISSUE TITLE
[Enhancement]: 系统变量的描述有误

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#753]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Reference/Variable/system-variables/system-variables-overview/#_6

<img width="747" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/91ef53c8-b03f-4a04-9759-0b54cb4ec9e7">

1. 这两句话本身就是自相矛盾的。
2. 现在也肯定不止只有sql_mode是生效的。

**Comment by lacrimosaprinz** [comment]
跟 @YANGGMM 已确认，现在仍然只是支持ONLY_FULL_GROUP_BY

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/766
https://github.com/matrixorigin/matrixorigin.io/pull/550
