### ISSUE TITLE
[Typo]: MoCloud文档上线

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixorigin.io.cn#762]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

【第一期文档站点需求】
- 前提：moc和mo文档分仓库
- 实现形式：moc文档生成一个新的网站
- moc文档url主域名(需要研发拟一个方案）：https://docs.matrixorigin.cn/cloud/topic_name
- 上线时间：10.15

**Comment by lacrimosaprinz** [comment]
moc不区分版本号

**Comment by dengn** [comment]
done
