### ISSUE TITLE
[Displaying]: matrixone打错了

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#764]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="678" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/f33d1036-0ff8-4bf8-b190-27510ee603e8">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/765
