### ISSUE TITLE
[Displaying]: 1.0.0-rc1官方文档页面没有编辑按钮

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixorigin.io.cn#775]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

 1.0.0-rc1的官方文档页面没有编辑按钮
![1695375929180](https://github.com/matrixorigin/matrixorigin.io.cn/assets/91644845/d89509c8-742a-4997-9f5c-d19cbb79a3d5)

**Comment by dengn** [comment]
fixed

**Comment by yanghaitao5000** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
