### ISSUE TITLE
[Typo]: decimal 类型描述不对

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#78]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

该问题由产品问题导致，修复后需要更新手册：
decimal类型一般不做decimal64和128区分，尽管我们一般嘴上会说，但说的时候指的是精度范围。desc table 时会显示成 decimal(x,y) 而不是 decimal64，可以参照 TiDB 或 MySQL 的手册描述（不过还是可以体现不同精度范围占用的空间大小不同这个信息）
 TiDB：https://docs.pingcap.com/zh/tidb/stable/data-type-numeric
MySQL：https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html

**Comment by lacrimosaprinz** [comment]
@LiSong0214   en/zh 已修改：https://docs.matrixorigin.io/cn/dev/MatrixOne/Reference/Data-Types/data-types/#decimalbeta
