### ISSUE TITLE
[Doc Request]:  需要一篇文章专门解释MO的锁机制

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#786]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

需要一篇文章专门解释MO的事务和锁机制实现

https://mp.weixin.qq.com/s?__biz=Mzg2NjU2ODUwMA==&mid=2247489184&idx=1&sn=f5e9835447c2e2e32394f79ec4154040&chksm=ce4986fbf93e0feddc0b134ff402fdeff3c5fd772fbd20cd6c3e287e01f7ef9452e66bf98e10#rd

直接把这篇文章修改一下发上去，补充到这个地方
<img width="756" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/8e732537-df2f-453c-898e-585580c5a122">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/788

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/560
