### ISSUE TITLE
[Enhancement]: 数据库模式设计的例子与 TiDB 相似度过高

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#79]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

建议对表名列名描述方式上有所区别，现在的相似度太高了

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/183
