### ISSUE TITLE
[Enhancement]: SSB测试更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#793]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Test/performance-testing/SSB-test-with-matrixone/#_4

<img width="768" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/2c8cc51c-5791-44c2-bbf8-d5b851884fed">

现在group by支持别名了，下面的sql语句也要更新下。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/800
https://github.com/matrixorigin/matrixorigin.io/pull/565
