### ISSUE TITLE
[Typo]: showtables标题错误

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#80]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/31049447/202373904-e7c67194-ed3d-4dd3-95d6-89318efa2743.png">

**Comment by lacrimosaprinz** [comment]
https://docs.matrixorigin.io/dev/MatrixOne/Develop/schema-design/create-table/#prevent-null-values      
https://docs.matrixorigin.io/cn/dev/MatrixOne/Develop/schema-design/create-table/#show-tables

已修复  @LiSong0214
