### ISSUE TITLE
[Typo]: PREFERED写错了，应该是PREFERRED

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#820]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="733" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/4744a10d-56c3-4465-81b6-778aee145c8c">

**Comment by cyann7** [comment]
申请关闭 @dengn
