### ISSUE TITLE
[Doc Request]: 1.0.0 更新 release包和release note

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#849]
### Is there an existing issue about this doc request?

- [X] I have checked the existing issues.

### Describe the doc request.

1.0.0已正式发布， 文档需要更新下 release包和release note

https://github.com/matrixorigin/matrixone/releases/tag/v1.0.0

**Comment by cyann7** [comment]
申请关闭 @dengn
