### ISSUE TITLE
[Enhancement]: 增加UPDATE的limitation

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#85]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

https://docs.matrixorigin.io/dev/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/update/

这里加个限制，我们目前不支持INSERT ON DUPLICATE KEY UPDATE

**Comment by lacrimosaprinz** [comment]
已添加 ，还未提交pr
