### ISSUE TITLE
[Enhancement]: 补充docker镜像tag为latest时为最新的稳定版本而非最新的main分支commit号的说明

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixorigin.io.cn#854]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

补充docker镜像tag为latest时为最新的稳定版本而非最新的main分支commit号的说明

**Comment by dengn** [comment]
verified.
