### ISSUE TITLE
[Enhancement]: 补充缺少的关键字说明

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixorigin.io.cn#855]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

根据文件查漏补缺，更新文档说明
./pkg/sql/parsers/dialect/mysql/keywords.go

比如visible

**Comment by cyann7** [comment]
https://docs.matrixorigin.cn/dev/MatrixOne/Reference/Language-Structure/keywords/

https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/parsers/dialect/mysql/keywords.go

**Comment by cyann7** [comment]
keywords.go 里面除了非保留关键字剩下的都是保留关键字

**Comment by dengn** [comment]
Verified.
