### ISSUE TITLE
[Enhancement]: partition的功能更新

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#892]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

1.1的partition功能需要更新文档。

**Comment by cyann7** [comment]
文档做出了以下改动：
- docs/MatrixOne/
	- Overview/
		- 修改partition的功能列表：1.1-matrixone-feature-list.md 去掉tag 替代了 matrixone-feature-list.md
		- feature/
			- 同步mysql兼容性：修改 mysql-compatibility.md
	- Performance-Tuning/optimization-concepts/through-partition/
		- 更新partition新功能：修改 through-partition-by.md
		- 更新partition-pruning新功能：修改 through-partition-pruning.md
		
	- Reference/
		- 修改partition的支持：修改 Limitations/mo-partition-support.md
		- 对partition的支持移动到other/partition新目录 ：移动到 Other/Partition/mo-partition-support.md

**Comment by dengn** [comment]
verified.
