### ISSUE TITLE
[Enhancement]: 使用 Docker 执行 Load Data 标题不准确

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#92]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/31049447/203921461-c07ab145-4a4d-4ab6-921f-a1faa44976b7.png">
这个标题描述的有点怪

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/143

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/111

**Comment by dengn** [comment]
fixed
