### ISSUE TITLE
[Enhancement]: 例子中创建表的地方建议在之前加一条创建库

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#93]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

文档中有很多地方，比如在数据读取这
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/31049447/203922390-dad55539-43f9-49d7-b01c-e759452aab24.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/143
