### ISSUE TITLE
[Enhancement]: DDL 语句改成可复制执行的方式

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#94]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

例如
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/31049447/203923158-65242a7a-d472-4547-a277-eb3daccfe5d5.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/143
