### ISSUE TITLE
[Enhancement]: 多种 Join 的描述及举例建议改一下

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#95]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

三种连接的样例描述基本一样且没有突出说明不同连接的处理效果，最好左右连接时数据中有一些 null 值说明更加清晰。另外，最好没种join 中只包含该类查询，理解起来比较简单。

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/189
