### ISSUE TITLE
[Enhancement]:  mo的压缩算法是什么

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixorigin.io.cn#955]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the enhancement.

用户提问：MO的列存压缩算法是什么？需要跟存储确认一下。

**Comment by yangj1211** [comment]
经与韩枫老师确认，基于压缩速度，还有使用的广泛程度考虑，mo目前列存采用LZ4压缩算法，且不支持配置成其它算法。

**Comment by dengn** [comment]
verified.
