### ISSUE TITLE
[Typo]: 关联子查询和无关联子查询的举例SQL 不等价

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#96]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="906" alt="image" src="https://user-images.githubusercontent.com/31049447/203924310-85ad6f05-0a12-422d-afe8-070c6e8cc1fd.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/189
