### ISSUE TITLE
[Typo]: autocommit 的值是 1 不是 on

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#97]
### Is there an existing issue about this typo?

- [X] I have checked the existing issues.

### Describe the issue

<img width="759" alt="image" src="https://user-images.githubusercontent.com/31049447/203924736-524b1704-da0a-4e70-9a39-ba35e1f7459b.png">

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io.cn/pull/127
