### ISSUE TITLE
[Displaying]: MVCC 的图挂了

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixorigin.io.cn#99]
### Is there an existing issue about this enhancement?

- [X] I have checked the existing issues.

### Describe the issue.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/31049447/203958840-e31f953c-f051-4420-ade4-a433d4392e56.png">

**Comment by lacrimosaprinz** [comment]
https://docs.matrixorigin.io/dev/MatrixOne/Reference/SQL-Reference/Transactions/distributed-transaction-overview/#mvcc    fixed
